name: PR Preview - README Update

on:
  pull_request:
    branches: [ "**" ]

permissions:
  pull-requests: write
  contents: read

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run README update script
        run: echo "Simulating README update..."

      - name: Show preview in PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: preview
          message: |
            ✅ README update preview completed!
            You can check the diff in this PR to see the updated README section.
