name: Update README with Recent Activity

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' 

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate activity list
        uses: readme-workflows/recent-activity@v2
        with:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}

      - name: Commit updated README
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "📄 Update README with recent activity"
          git push

